### ISSUE TITLE
翻訳：design-guide/foundations/colors/

### ISSUE THREAD

**Issue by ebicology** [jawordpressorg/design-handbook#33]
以下のページの翻訳をします。

**翻訳するページのURL**

https://make.wordpress.org/design/handbook/design-guide/foundations/colors/

**翻訳するページのリポジトリ内のパス**

design-handbook/design/design-guide/foundations/colors.md

**原文との差分チェック**

- [x] 原文ページとリポジトリ内の内容が同じものか確認済み（ざっくりで良いです）

**Comment by miminari** [comment]
#62
